### PR TITLE
Fix PipelineList method to return result

### LINKED ISSUE #57: Fix PipelineList method to return result

### PR DESCRIPTION
**Pull request by subham9418**
closes #57

### CODE REVIEW

**Comment by mars** [comment]
These method's code is autogenerated, so while this does seem to fix the issue, what we really need fixed is the Heroku API schema generating this correctly. I've investigated the schema, but don't see anything that would cause this one List method to be broken like this.

Maybe this is a bug in the code generator, or something nuanced in the schema itself.

**Comment by jcomo** [comment]
@mars the issue appears to be in the schema. I tested by downloading the latest schema from https://api.heroku.com/schema and noticed that the "type" key was not nested properly under targetSchema

Updating the schema as shown in the diff below, and then running `./script/generate -n` produced the correct code output.

```diff
diff --git a/v5/schema.json b/v5/schema.json
index 3536cb5..0028a67 100644
--- a/v5/schema.json
+++ b/v5/schema.json
@@ -10830,11 +10830,11 @@
           "targetSchema": {
             "items": {
               "$ref": "#/definitions/pipeline"
-            }
+            },
+            "type": [
+              "array"
+            ]
           },
-          "type": [
-            "array"
-          ],
           "title": "List"
         }
       ],
```

Without knowing how the schemas are actually generated on your end, that's as far as I can get!

One thing to consider separately: this _may_ be a bug in schematic. It seems like it should throw an error for an invalid schema (that is, assuming this isn't a valid schema structure for some other use case)

**Comment by mars** [comment]
Thanks for the details @jcomo 😄  I've dug into this schema issue and believe I have a fix ready. It just has to make it through a series of internal reviews, and then propagation out to the public-facing schema JSON. Hopefully I can report that it is fixed next week 🤞

**Comment by jcomo** [comment]
Thanks for the quick response and fix @mars!

**Comment by mars** [comment]
Thanks for your patience as we worked through a release of this schema fix, now ready for review at #61.

Closing this PR, since it is not the correct solution.

**Pull request closed without merging**
